version: 2
jobs:
  install_ruby_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v5-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle install --deployment
      - save_cache:
          paths:
            - vendor/bundle
          key: ruby-dependencies-v5-{{ checksum "Gemfile.lock" }}

  install_javascript_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: javascript-dependencies-v1-{{ checksum "yarn.lock" }}

  run_rubocop:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v5-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          command: bundle config --local path vendor/bundle
      - run:
          command: bundle exec rubocop

  run_reek:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v5-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          command: bundle config --local path vendor/bundle
      - run:
          command: bundle exec reek

  run_brakeman:
    docker:
      - image: circleci/ruby:2.5.1-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-v5-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - javascript-dependencies-v1-{{ checksum "yarn.lock" }}
      - run:
          command: bundle config --local path vendor/bundle
      - run:
          command: bundle exec brakeman

workflows:
  version: 2
  main:
    jobs:
      - install_ruby_dependencies
      - install_javascript_dependencies
      - run_rubocop:
          requires:
            - install_ruby_dependencies
      - run_reek:
          requires:
            - install_ruby_dependencies
      - run_brakeman:
          requires:
            - install_ruby_dependencies
