development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: rails_development

test:
  adapter: postgresql
  host: localhost
  username: postgres
  database: rails_test

production:
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>
